/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentIdRouteImport } from './routes/$agentId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as AgentIdSkillsRouteImport } from './routes/$agentId/skills'
import { Route as AgentIdSchedulesRouteImport } from './routes/$agentId/schedules'
import { Route as AgentIdChatRouteImport } from './routes/$agentId/chat'
import { Route as AgentIdAppsRouteImport } from './routes/$agentId/apps'
import { Route as ApiPreviewIdSplatRouteImport } from './routes/api/preview/$id/$'
import { Route as ApiAppsSlugSplatRouteImport } from './routes/api/apps/$slug/$'
import { Route as ApiAgentAgentIdSplatRouteImport } from './routes/api/agent/$agentId/$'
import { Route as ApiDeployAgentIdDeployIdSplatRouteImport } from './routes/api/deploy/$agentId/$deployId/$'

const AgentIdRoute = AgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdSkillsRoute = AgentIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentIdRoute,
} as any)
const AgentIdSchedulesRoute = AgentIdSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AgentIdRoute,
} as any)
const AgentIdChatRoute = AgentIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentIdRoute,
} as any)
const AgentIdAppsRoute = AgentIdAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AgentIdRoute,
} as any)
const ApiPreviewIdSplatRoute = ApiPreviewIdSplatRouteImport.update({
  id: '/api/preview/$id/$',
  path: '/api/preview/$id/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppsSlugSplatRoute = ApiAppsSlugSplatRouteImport.update({
  id: '/api/apps/$slug/$',
  path: '/api/apps/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAgentIdSplatRoute = ApiAgentAgentIdSplatRouteImport.update({
  id: '/api/agent/$agentId/$',
  path: '/api/agent/$agentId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeployAgentIdDeployIdSplatRoute =
  ApiDeployAgentIdDeployIdSplatRouteImport.update({
    id: '/api/deploy/$agentId/$deployId/$',
    path: '/api/deploy/$agentId/$deployId/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$agentId': typeof AgentIdRouteWithChildren
  '/$agentId/apps': typeof AgentIdAppsRoute
  '/$agentId/chat': typeof AgentIdChatRoute
  '/$agentId/schedules': typeof AgentIdSchedulesRoute
  '/$agentId/skills': typeof AgentIdSkillsRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/agent/$agentId/$': typeof ApiAgentAgentIdSplatRoute
  '/api/apps/$slug/$': typeof ApiAppsSlugSplatRoute
  '/api/preview/$id/$': typeof ApiPreviewIdSplatRoute
  '/api/deploy/$agentId/$deployId/$': typeof ApiDeployAgentIdDeployIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$agentId': typeof AgentIdRouteWithChildren
  '/$agentId/apps': typeof AgentIdAppsRoute
  '/$agentId/chat': typeof AgentIdChatRoute
  '/$agentId/schedules': typeof AgentIdSchedulesRoute
  '/$agentId/skills': typeof AgentIdSkillsRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/agent/$agentId/$': typeof ApiAgentAgentIdSplatRoute
  '/api/apps/$slug/$': typeof ApiAppsSlugSplatRoute
  '/api/preview/$id/$': typeof ApiPreviewIdSplatRoute
  '/api/deploy/$agentId/$deployId/$': typeof ApiDeployAgentIdDeployIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$agentId': typeof AgentIdRouteWithChildren
  '/$agentId/apps': typeof AgentIdAppsRoute
  '/$agentId/chat': typeof AgentIdChatRoute
  '/$agentId/schedules': typeof AgentIdSchedulesRoute
  '/$agentId/skills': typeof AgentIdSkillsRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/agent/$agentId/$': typeof ApiAgentAgentIdSplatRoute
  '/api/apps/$slug/$': typeof ApiAppsSlugSplatRoute
  '/api/preview/$id/$': typeof ApiPreviewIdSplatRoute
  '/api/deploy/$agentId/$deployId/$': typeof ApiDeployAgentIdDeployIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$agentId'
    | '/$agentId/apps'
    | '/$agentId/chat'
    | '/$agentId/schedules'
    | '/$agentId/skills'
    | '/api/agents'
    | '/api/agent/$agentId/$'
    | '/api/apps/$slug/$'
    | '/api/preview/$id/$'
    | '/api/deploy/$agentId/$deployId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$agentId'
    | '/$agentId/apps'
    | '/$agentId/chat'
    | '/$agentId/schedules'
    | '/$agentId/skills'
    | '/api/agents'
    | '/api/agent/$agentId/$'
    | '/api/apps/$slug/$'
    | '/api/preview/$id/$'
    | '/api/deploy/$agentId/$deployId/$'
  id:
    | '__root__'
    | '/'
    | '/$agentId'
    | '/$agentId/apps'
    | '/$agentId/chat'
    | '/$agentId/schedules'
    | '/$agentId/skills'
    | '/api/agents'
    | '/api/agent/$agentId/$'
    | '/api/apps/$slug/$'
    | '/api/preview/$id/$'
    | '/api/deploy/$agentId/$deployId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentIdRoute: typeof AgentIdRouteWithChildren
  ApiAgentsRoute: typeof ApiAgentsRoute
  ApiAgentAgentIdSplatRoute: typeof ApiAgentAgentIdSplatRoute
  ApiAppsSlugSplatRoute: typeof ApiAppsSlugSplatRoute
  ApiPreviewIdSplatRoute: typeof ApiPreviewIdSplatRoute
  ApiDeployAgentIdDeployIdSplatRoute: typeof ApiDeployAgentIdDeployIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$agentId': {
      id: '/$agentId'
      path: '/$agentId'
      fullPath: '/$agentId'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$agentId/skills': {
      id: '/$agentId/skills'
      path: '/skills'
      fullPath: '/$agentId/skills'
      preLoaderRoute: typeof AgentIdSkillsRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/$agentId/schedules': {
      id: '/$agentId/schedules'
      path: '/schedules'
      fullPath: '/$agentId/schedules'
      preLoaderRoute: typeof AgentIdSchedulesRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/$agentId/chat': {
      id: '/$agentId/chat'
      path: '/chat'
      fullPath: '/$agentId/chat'
      preLoaderRoute: typeof AgentIdChatRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/$agentId/apps': {
      id: '/$agentId/apps'
      path: '/apps'
      fullPath: '/$agentId/apps'
      preLoaderRoute: typeof AgentIdAppsRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/api/preview/$id/$': {
      id: '/api/preview/$id/$'
      path: '/api/preview/$id/$'
      fullPath: '/api/preview/$id/$'
      preLoaderRoute: typeof ApiPreviewIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps/$slug/$': {
      id: '/api/apps/$slug/$'
      path: '/api/apps/$slug/$'
      fullPath: '/api/apps/$slug/$'
      preLoaderRoute: typeof ApiAppsSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$agentId/$': {
      id: '/api/agent/$agentId/$'
      path: '/api/agent/$agentId/$'
      fullPath: '/api/agent/$agentId/$'
      preLoaderRoute: typeof ApiAgentAgentIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deploy/$agentId/$deployId/$': {
      id: '/api/deploy/$agentId/$deployId/$'
      path: '/api/deploy/$agentId/$deployId/$'
      fullPath: '/api/deploy/$agentId/$deployId/$'
      preLoaderRoute: typeof ApiDeployAgentIdDeployIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentIdRouteChildren {
  AgentIdAppsRoute: typeof AgentIdAppsRoute
  AgentIdChatRoute: typeof AgentIdChatRoute
  AgentIdSchedulesRoute: typeof AgentIdSchedulesRoute
  AgentIdSkillsRoute: typeof AgentIdSkillsRoute
}

const AgentIdRouteChildren: AgentIdRouteChildren = {
  AgentIdAppsRoute: AgentIdAppsRoute,
  AgentIdChatRoute: AgentIdChatRoute,
  AgentIdSchedulesRoute: AgentIdSchedulesRoute,
  AgentIdSkillsRoute: AgentIdSkillsRoute,
}

const AgentIdRouteWithChildren =
  AgentIdRoute._addFileChildren(AgentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentIdRoute: AgentIdRouteWithChildren,
  ApiAgentsRoute: ApiAgentsRoute,
  ApiAgentAgentIdSplatRoute: ApiAgentAgentIdSplatRoute,
  ApiAppsSlugSplatRoute: ApiAppsSlugSplatRoute,
  ApiPreviewIdSplatRoute: ApiPreviewIdSplatRoute,
  ApiDeployAgentIdDeployIdSplatRoute: ApiDeployAgentIdDeployIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
