/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentIdRouteImport } from './routes/$agentId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIdIndexRouteImport } from './routes/$agentId/index'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as AgentIdSkillsRouteImport } from './routes/$agentId/skills'
import { Route as AgentIdSchedulesRouteImport } from './routes/$agentId/schedules'
import { Route as AgentIdChatRouteImport } from './routes/$agentId/chat'
import { Route as AgentIdChannelsRouteImport } from './routes/$agentId/channels'
import { Route as AgentIdAppsRouteImport } from './routes/$agentId/apps'
import { Route as AgentIdSessionIdRouteImport } from './routes/$agentId/$sessionId'
import { Route as TelegramWebhookAccountIdRouteImport } from './routes/telegram/webhook/$accountId'
import { Route as AgentIdSessionIdSkillsRouteImport } from './routes/$agentId/$sessionId/skills'
import { Route as AgentIdSessionIdSchedulesRouteImport } from './routes/$agentId/$sessionId/schedules'
import { Route as AgentIdSessionIdChatRouteImport } from './routes/$agentId/$sessionId/chat'
import { Route as AgentIdSessionIdChannelsRouteImport } from './routes/$agentId/$sessionId/channels'
import { Route as AgentIdSessionIdAppsRouteImport } from './routes/$agentId/$sessionId/apps'
import { Route as ApiPreviewIdSplatRouteImport } from './routes/api/preview/$id/$'
import { Route as ApiAppsSlugSplatRouteImport } from './routes/api/apps/$slug/$'
import { Route as ApiAgentAgentIdSplatRouteImport } from './routes/api/agent/$agentId/$'
import { Route as ApiDeployAgentIdDeployIdSplatRouteImport } from './routes/api/deploy/$agentId/$deployId/$'

const AgentIdRoute = AgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdIndexRoute = AgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentIdRoute,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdSkillsRoute = AgentIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentIdRoute,
} as any)
const AgentIdSchedulesRoute = AgentIdSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AgentIdRoute,
} as any)
const AgentIdChatRoute = AgentIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentIdRoute,
} as any)
const AgentIdChannelsRoute = AgentIdChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AgentIdRoute,
} as any)
const AgentIdAppsRoute = AgentIdAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AgentIdRoute,
} as any)
const AgentIdSessionIdRoute = AgentIdSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AgentIdRoute,
} as any)
const TelegramWebhookAccountIdRoute =
  TelegramWebhookAccountIdRouteImport.update({
    id: '/telegram/webhook/$accountId',
    path: '/telegram/webhook/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentIdSessionIdSkillsRoute = AgentIdSessionIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentIdSessionIdRoute,
} as any)
const AgentIdSessionIdSchedulesRoute =
  AgentIdSessionIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AgentIdSessionIdRoute,
  } as any)
const AgentIdSessionIdChatRoute = AgentIdSessionIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentIdSessionIdRoute,
} as any)
const AgentIdSessionIdChannelsRoute =
  AgentIdSessionIdChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AgentIdSessionIdRoute,
  } as any)
const AgentIdSessionIdAppsRoute = AgentIdSessionIdAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AgentIdSessionIdRoute,
} as any)
const ApiPreviewIdSplatRoute = ApiPreviewIdSplatRouteImport.update({
  id: '/api/preview/$id/$',
  path: '/api/preview/$id/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppsSlugSplatRoute = ApiAppsSlugSplatRouteImport.update({
  id: '/api/apps/$slug/$',
  path: '/api/apps/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAgentIdSplatRoute = ApiAgentAgentIdSplatRouteImport.update({
  id: '/api/agent/$agentId/$',
  path: '/api/agent/$agentId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeployAgentIdDeployIdSplatRoute =
  ApiDeployAgentIdDeployIdSplatRouteImport.update({
    id: '/api/deploy/$agentId/$deployId/$',
    path: '/api/deploy/$agentId/$deployId/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$agentId': typeof AgentIdRouteWithChildren
  '/$agentId/$sessionId': typeof AgentIdSessionIdRouteWithChildren
  '/$agentId/apps': typeof AgentIdAppsRoute
  '/$agentId/channels': typeof AgentIdChannelsRoute
  '/$agentId/chat': typeof AgentIdChatRoute
  '/$agentId/schedules': typeof AgentIdSchedulesRoute
  '/$agentId/skills': typeof AgentIdSkillsRoute
  '/api/agents': typeof ApiAgentsRoute
  '/$agentId/': typeof AgentIdIndexRoute
  '/$agentId/$sessionId/apps': typeof AgentIdSessionIdAppsRoute
  '/$agentId/$sessionId/channels': typeof AgentIdSessionIdChannelsRoute
  '/$agentId/$sessionId/chat': typeof AgentIdSessionIdChatRoute
  '/$agentId/$sessionId/schedules': typeof AgentIdSessionIdSchedulesRoute
  '/$agentId/$sessionId/skills': typeof AgentIdSessionIdSkillsRoute
  '/telegram/webhook/$accountId': typeof TelegramWebhookAccountIdRoute
  '/api/agent/$agentId/$': typeof ApiAgentAgentIdSplatRoute
  '/api/apps/$slug/$': typeof ApiAppsSlugSplatRoute
  '/api/preview/$id/$': typeof ApiPreviewIdSplatRoute
  '/api/deploy/$agentId/$deployId/$': typeof ApiDeployAgentIdDeployIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$agentId/$sessionId': typeof AgentIdSessionIdRouteWithChildren
  '/$agentId/apps': typeof AgentIdAppsRoute
  '/$agentId/channels': typeof AgentIdChannelsRoute
  '/$agentId/chat': typeof AgentIdChatRoute
  '/$agentId/schedules': typeof AgentIdSchedulesRoute
  '/$agentId/skills': typeof AgentIdSkillsRoute
  '/api/agents': typeof ApiAgentsRoute
  '/$agentId': typeof AgentIdIndexRoute
  '/$agentId/$sessionId/apps': typeof AgentIdSessionIdAppsRoute
  '/$agentId/$sessionId/channels': typeof AgentIdSessionIdChannelsRoute
  '/$agentId/$sessionId/chat': typeof AgentIdSessionIdChatRoute
  '/$agentId/$sessionId/schedules': typeof AgentIdSessionIdSchedulesRoute
  '/$agentId/$sessionId/skills': typeof AgentIdSessionIdSkillsRoute
  '/telegram/webhook/$accountId': typeof TelegramWebhookAccountIdRoute
  '/api/agent/$agentId/$': typeof ApiAgentAgentIdSplatRoute
  '/api/apps/$slug/$': typeof ApiAppsSlugSplatRoute
  '/api/preview/$id/$': typeof ApiPreviewIdSplatRoute
  '/api/deploy/$agentId/$deployId/$': typeof ApiDeployAgentIdDeployIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$agentId': typeof AgentIdRouteWithChildren
  '/$agentId/$sessionId': typeof AgentIdSessionIdRouteWithChildren
  '/$agentId/apps': typeof AgentIdAppsRoute
  '/$agentId/channels': typeof AgentIdChannelsRoute
  '/$agentId/chat': typeof AgentIdChatRoute
  '/$agentId/schedules': typeof AgentIdSchedulesRoute
  '/$agentId/skills': typeof AgentIdSkillsRoute
  '/api/agents': typeof ApiAgentsRoute
  '/$agentId/': typeof AgentIdIndexRoute
  '/$agentId/$sessionId/apps': typeof AgentIdSessionIdAppsRoute
  '/$agentId/$sessionId/channels': typeof AgentIdSessionIdChannelsRoute
  '/$agentId/$sessionId/chat': typeof AgentIdSessionIdChatRoute
  '/$agentId/$sessionId/schedules': typeof AgentIdSessionIdSchedulesRoute
  '/$agentId/$sessionId/skills': typeof AgentIdSessionIdSkillsRoute
  '/telegram/webhook/$accountId': typeof TelegramWebhookAccountIdRoute
  '/api/agent/$agentId/$': typeof ApiAgentAgentIdSplatRoute
  '/api/apps/$slug/$': typeof ApiAppsSlugSplatRoute
  '/api/preview/$id/$': typeof ApiPreviewIdSplatRoute
  '/api/deploy/$agentId/$deployId/$': typeof ApiDeployAgentIdDeployIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$agentId'
    | '/$agentId/$sessionId'
    | '/$agentId/apps'
    | '/$agentId/channels'
    | '/$agentId/chat'
    | '/$agentId/schedules'
    | '/$agentId/skills'
    | '/api/agents'
    | '/$agentId/'
    | '/$agentId/$sessionId/apps'
    | '/$agentId/$sessionId/channels'
    | '/$agentId/$sessionId/chat'
    | '/$agentId/$sessionId/schedules'
    | '/$agentId/$sessionId/skills'
    | '/telegram/webhook/$accountId'
    | '/api/agent/$agentId/$'
    | '/api/apps/$slug/$'
    | '/api/preview/$id/$'
    | '/api/deploy/$agentId/$deployId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$agentId/$sessionId'
    | '/$agentId/apps'
    | '/$agentId/channels'
    | '/$agentId/chat'
    | '/$agentId/schedules'
    | '/$agentId/skills'
    | '/api/agents'
    | '/$agentId'
    | '/$agentId/$sessionId/apps'
    | '/$agentId/$sessionId/channels'
    | '/$agentId/$sessionId/chat'
    | '/$agentId/$sessionId/schedules'
    | '/$agentId/$sessionId/skills'
    | '/telegram/webhook/$accountId'
    | '/api/agent/$agentId/$'
    | '/api/apps/$slug/$'
    | '/api/preview/$id/$'
    | '/api/deploy/$agentId/$deployId/$'
  id:
    | '__root__'
    | '/'
    | '/$agentId'
    | '/$agentId/$sessionId'
    | '/$agentId/apps'
    | '/$agentId/channels'
    | '/$agentId/chat'
    | '/$agentId/schedules'
    | '/$agentId/skills'
    | '/api/agents'
    | '/$agentId/'
    | '/$agentId/$sessionId/apps'
    | '/$agentId/$sessionId/channels'
    | '/$agentId/$sessionId/chat'
    | '/$agentId/$sessionId/schedules'
    | '/$agentId/$sessionId/skills'
    | '/telegram/webhook/$accountId'
    | '/api/agent/$agentId/$'
    | '/api/apps/$slug/$'
    | '/api/preview/$id/$'
    | '/api/deploy/$agentId/$deployId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentIdRoute: typeof AgentIdRouteWithChildren
  ApiAgentsRoute: typeof ApiAgentsRoute
  TelegramWebhookAccountIdRoute: typeof TelegramWebhookAccountIdRoute
  ApiAgentAgentIdSplatRoute: typeof ApiAgentAgentIdSplatRoute
  ApiAppsSlugSplatRoute: typeof ApiAppsSlugSplatRoute
  ApiPreviewIdSplatRoute: typeof ApiPreviewIdSplatRoute
  ApiDeployAgentIdDeployIdSplatRoute: typeof ApiDeployAgentIdDeployIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$agentId': {
      id: '/$agentId'
      path: '/$agentId'
      fullPath: '/$agentId'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$agentId/': {
      id: '/$agentId/'
      path: '/'
      fullPath: '/$agentId/'
      preLoaderRoute: typeof AgentIdIndexRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$agentId/skills': {
      id: '/$agentId/skills'
      path: '/skills'
      fullPath: '/$agentId/skills'
      preLoaderRoute: typeof AgentIdSkillsRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/$agentId/schedules': {
      id: '/$agentId/schedules'
      path: '/schedules'
      fullPath: '/$agentId/schedules'
      preLoaderRoute: typeof AgentIdSchedulesRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/$agentId/chat': {
      id: '/$agentId/chat'
      path: '/chat'
      fullPath: '/$agentId/chat'
      preLoaderRoute: typeof AgentIdChatRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/$agentId/channels': {
      id: '/$agentId/channels'
      path: '/channels'
      fullPath: '/$agentId/channels'
      preLoaderRoute: typeof AgentIdChannelsRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/$agentId/apps': {
      id: '/$agentId/apps'
      path: '/apps'
      fullPath: '/$agentId/apps'
      preLoaderRoute: typeof AgentIdAppsRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/$agentId/$sessionId': {
      id: '/$agentId/$sessionId'
      path: '/$sessionId'
      fullPath: '/$agentId/$sessionId'
      preLoaderRoute: typeof AgentIdSessionIdRouteImport
      parentRoute: typeof AgentIdRoute
    }
    '/telegram/webhook/$accountId': {
      id: '/telegram/webhook/$accountId'
      path: '/telegram/webhook/$accountId'
      fullPath: '/telegram/webhook/$accountId'
      preLoaderRoute: typeof TelegramWebhookAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$agentId/$sessionId/skills': {
      id: '/$agentId/$sessionId/skills'
      path: '/skills'
      fullPath: '/$agentId/$sessionId/skills'
      preLoaderRoute: typeof AgentIdSessionIdSkillsRouteImport
      parentRoute: typeof AgentIdSessionIdRoute
    }
    '/$agentId/$sessionId/schedules': {
      id: '/$agentId/$sessionId/schedules'
      path: '/schedules'
      fullPath: '/$agentId/$sessionId/schedules'
      preLoaderRoute: typeof AgentIdSessionIdSchedulesRouteImport
      parentRoute: typeof AgentIdSessionIdRoute
    }
    '/$agentId/$sessionId/chat': {
      id: '/$agentId/$sessionId/chat'
      path: '/chat'
      fullPath: '/$agentId/$sessionId/chat'
      preLoaderRoute: typeof AgentIdSessionIdChatRouteImport
      parentRoute: typeof AgentIdSessionIdRoute
    }
    '/$agentId/$sessionId/channels': {
      id: '/$agentId/$sessionId/channels'
      path: '/channels'
      fullPath: '/$agentId/$sessionId/channels'
      preLoaderRoute: typeof AgentIdSessionIdChannelsRouteImport
      parentRoute: typeof AgentIdSessionIdRoute
    }
    '/$agentId/$sessionId/apps': {
      id: '/$agentId/$sessionId/apps'
      path: '/apps'
      fullPath: '/$agentId/$sessionId/apps'
      preLoaderRoute: typeof AgentIdSessionIdAppsRouteImport
      parentRoute: typeof AgentIdSessionIdRoute
    }
    '/api/preview/$id/$': {
      id: '/api/preview/$id/$'
      path: '/api/preview/$id/$'
      fullPath: '/api/preview/$id/$'
      preLoaderRoute: typeof ApiPreviewIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps/$slug/$': {
      id: '/api/apps/$slug/$'
      path: '/api/apps/$slug/$'
      fullPath: '/api/apps/$slug/$'
      preLoaderRoute: typeof ApiAppsSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$agentId/$': {
      id: '/api/agent/$agentId/$'
      path: '/api/agent/$agentId/$'
      fullPath: '/api/agent/$agentId/$'
      preLoaderRoute: typeof ApiAgentAgentIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deploy/$agentId/$deployId/$': {
      id: '/api/deploy/$agentId/$deployId/$'
      path: '/api/deploy/$agentId/$deployId/$'
      fullPath: '/api/deploy/$agentId/$deployId/$'
      preLoaderRoute: typeof ApiDeployAgentIdDeployIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentIdSessionIdRouteChildren {
  AgentIdSessionIdAppsRoute: typeof AgentIdSessionIdAppsRoute
  AgentIdSessionIdChannelsRoute: typeof AgentIdSessionIdChannelsRoute
  AgentIdSessionIdChatRoute: typeof AgentIdSessionIdChatRoute
  AgentIdSessionIdSchedulesRoute: typeof AgentIdSessionIdSchedulesRoute
  AgentIdSessionIdSkillsRoute: typeof AgentIdSessionIdSkillsRoute
}

const AgentIdSessionIdRouteChildren: AgentIdSessionIdRouteChildren = {
  AgentIdSessionIdAppsRoute: AgentIdSessionIdAppsRoute,
  AgentIdSessionIdChannelsRoute: AgentIdSessionIdChannelsRoute,
  AgentIdSessionIdChatRoute: AgentIdSessionIdChatRoute,
  AgentIdSessionIdSchedulesRoute: AgentIdSessionIdSchedulesRoute,
  AgentIdSessionIdSkillsRoute: AgentIdSessionIdSkillsRoute,
}

const AgentIdSessionIdRouteWithChildren =
  AgentIdSessionIdRoute._addFileChildren(AgentIdSessionIdRouteChildren)

interface AgentIdRouteChildren {
  AgentIdSessionIdRoute: typeof AgentIdSessionIdRouteWithChildren
  AgentIdAppsRoute: typeof AgentIdAppsRoute
  AgentIdChannelsRoute: typeof AgentIdChannelsRoute
  AgentIdChatRoute: typeof AgentIdChatRoute
  AgentIdSchedulesRoute: typeof AgentIdSchedulesRoute
  AgentIdSkillsRoute: typeof AgentIdSkillsRoute
  AgentIdIndexRoute: typeof AgentIdIndexRoute
}

const AgentIdRouteChildren: AgentIdRouteChildren = {
  AgentIdSessionIdRoute: AgentIdSessionIdRouteWithChildren,
  AgentIdAppsRoute: AgentIdAppsRoute,
  AgentIdChannelsRoute: AgentIdChannelsRoute,
  AgentIdChatRoute: AgentIdChatRoute,
  AgentIdSchedulesRoute: AgentIdSchedulesRoute,
  AgentIdSkillsRoute: AgentIdSkillsRoute,
  AgentIdIndexRoute: AgentIdIndexRoute,
}

const AgentIdRouteWithChildren =
  AgentIdRoute._addFileChildren(AgentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentIdRoute: AgentIdRouteWithChildren,
  ApiAgentsRoute: ApiAgentsRoute,
  TelegramWebhookAccountIdRoute: TelegramWebhookAccountIdRoute,
  ApiAgentAgentIdSplatRoute: ApiAgentAgentIdSplatRoute,
  ApiAppsSlugSplatRoute: ApiAppsSlugSplatRoute,
  ApiPreviewIdSplatRoute: ApiPreviewIdSplatRoute,
  ApiDeployAgentIdDeployIdSplatRoute: ApiDeployAgentIdDeployIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
