#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const entry = join(root, "src/bundle/index.ts");
const outJs = join(root, "dist/bundle-runtime.js");
const outSource = join(root, "dist/bundle-runtime-source.js");
const outSourceDts = join(root, "dist/bundle-runtime-source.d.ts");

await mkdir(dirname(outJs), { recursive: true });

const build = await Bun.build({
  entrypoints: [entry],
  outdir: dirname(outJs),
  target: "browser",
  format: "esm",
  naming: "bundle-runtime.js",
  external: ["cloudflare:workers", "cloudflare:sockets", "@sinclair/typebox"],
  minify: false,
  sourcemap: "none",
});

if (!build.success) {
  for (const log of build.logs) console.error(log);
  process.exit(1);
}

const bundled = await readFile(outJs, "utf8");
const escaped = JSON.stringify(bundled);
await writeFile(
  outSource,
  `// Auto-generated by build.ts — do not edit.\nexport const BUNDLE_RUNTIME_SOURCE = ${escaped};\n`,
);
await writeFile(outSourceDts, "export declare const BUNDLE_RUNTIME_SOURCE: string;\n");

console.log(
  `[agent-bundle] built bundle-runtime.js (${bundled.length} bytes) and bundle-runtime-source.js`,
);
